config/routes.rb
AnimalTracker::Application.routes.draw do
  mount ActionCable.server => '/cable'
  resource :facebook_accounts, only: [:new, :destroy]
  get 'callback/facebook/:id', to: 'facebook_accounts#callback', as: :facebook_callback
  post 'facebook_accounts/send_wall_post', to: 'facebook_accounts#send_wall_post'
  delete 'facebook_accounts/:id', to: 'facebook_accounts#destroy'

  resource :twitter_accounts, only: [:new, :destroy]
  get 'callback/twitter', to: 'twitter_accounts#callback', as: :twitter_callback
  post 'twitter_accounts/send_tweet', to: 'twitter_accounts#send_tweet'
  delete 'twitter_accounts/:id', to: 'twitter_accounts#destroy'

  get '/animals/not_available', to: 'animals#not_available'
  resources :animals, only: [:show, :index]

  resources :organizations, only: [:show]

  resources :posts, only: [:show, :index]

  post 'wordpress_accounts/send_blog_post', to: 'admin/wordpress_accounts#send_blog_post'
  get 'send-to-adopt-a-pet', to: 'admin/adopt_a_pet_accounts#send_animal'

  devise_for :users
  get 'home/index'
  root to: 'home#index'
  get 'about', to: 'home#about'
  get 'features', to: 'home#features'
  get 'privacy-and-terms-of-service', to: 'home#privacy'
  get 'why-hospitium', to: 'home#why'
  get 'recent-changes', to: 'home#changes'
  get 'posts/feed/rss', to: 'posts#feed'

  devise_scope :user do
    put 'users/:id', to: 'users#update'
    delete 'users/sign_out', to: 'devise/session#destroy'
  end

  # Prefix route urls with "admin"
  namespace :admin do
    root to: 'home#index'

    resources :species,
              :statuses,
              :animal_colors,
              :shelters,
              :animal_weights,
              :adoption_contacts,
              :organizations,
              :relinquishment_contacts,
              :vet_contacts,
              :volunteer_contacts,
              :notifications,
              :posts,
              :notes,
              :documents,
              :shots,
              :adopt_a_pet_accounts,
              :wordpress_accounts,
              :adopt_animals,
              :relinquish_animals,
              :foster_contacts,
              :foster_animals,
              :contact_notes

    resources :animals do
      resources :animal_weights, :documents, :shots, :notes, :adoption_contacts, :relinquishment_contacts
      member do
        get 'cage_card'
        get 'duplicate'
        get 'qr_code'
        patch 'add_image'
      end
    end

    resources :users do
      member do
        get 'reset_token', to: 'users#reset_token'
        put 'set_role', to: 'users#set_role', as: 'user_role'
        delete 'cancel', to: 'users#cancel', as: 'cancel_user'
      end
    end
  end

  # post SecureHeaders::ContentSecurityPolicy::FF_CSP_ENDPOINT => 'content_security_policy#scribe'
end

app/models/adoption_contact.rb
class AdoptionContact < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  include CommonScopes
  include PublicActivity::Model
  tracked owner: ->(controller, _model) { controller.current_user },
          recipient: ->(controller, _model) { controller.current_user.organization },
          params: {
            author_name: ->(controller, _model) { controller.current_user.username },
            author_email: ->(controller, _model) { controller.current_user.email },
            object_name: ->(_controller, model) { "#{model.first_name} #{model.last_name}" },
            summary: ->(_controller, model) { model.changes }
          }

  has_many :adopt_animals
  has_many :animals, through: :adopt_animals
  has_many :contact_notes, as: :noteable
  belongs_to :organization
  before_create :modify_phone_number
  before_update :modify_phone_number

  attr_accessible :first_name, :last_name, :address, :phone, :email, :adopted_date

  validates :first_name, :last_name, :address, :organization_id, presence: true

  accepts_nested_attributes_for :adopt_animals

  # remove all characters from phone number except digits
  def modify_phone_number
    self.phone = phone.delete('^0-9') unless phone.blank?
  end

  def formatted_phone
    phone.blank? ? '' : number_to_phone(phone)
  end

  # ===============
  # = CSV support =
  # ===============
  comma do
    id 'ID'
    first_name 'First Name'
    last_name 'Last Name'
    address 'Address'
    phone 'Phone'
    email 'Email'
    animals 'Adopted Animal IDs' do |a| a.map(&:id).join(',') end
  end
end

app/controllers/admin/adoption_contacts_controller.rb
class Admin::AdoptionContactsController < Admin::CrudController
  load_and_authorize_resource
  include PublicActivity::StoreController

  respond_to :html, :json, :csv, :vcf

  # Allowed params for create and update
  self.permitted_attrs = [:first_name, :last_name, :phone, :email, :adopted_date, :address]
  # scope create to current_user.organization
  self.save_as_organization = true

  # GET /adoption_contacts
  # GET /adoption_contacts.xml
  def index
    @presenter = Admin::AdoptionContacts::IndexPresenter.new(current_user, params[:page], params[:q], params[:animal_id])
    respond_with(@adoption_contacts) do |format|
      format.html
      format.csv do
        render csv: AdoptionContact.organization(current_user),
               filename: 'adoption_contacts'
      end
    end
  end

  # GET /adoption_contacts/1
  # GET /adoption_contacts/1.xml
  def show
    @adoption_contact = AdoptionContact.find(params[:id])
    @animals = AdoptionContact.find(params[:id]).animals
    @adoptable_animals = Animal.organization(current_user)
    @contact_notes = ContactNote.where(noteable_id: @adoption_contact.id, noteable_type: 'AdoptionContact').order(created_at: 'ASC')

    respond_with(@adoption_contact)
  end
end

app/views/admin/adoption_contacts/_form.html.erb
<div class="row">
	<div class="col-sm-12 col-md-12 col-lg-12">
		<div class="block-flat clearfix">
			<div class="col-sm-12 col-md-12 col-lg-5">
				<%= form_for adoption_contact, :url => admin_adoption_contacts_path, :validate => true do |f| %>
				  <% if adoption_contact.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(adoption_contact.errors.count, "error") %> prohibited this adoption_contact from being saved:</h2>

				      <ul>
				      <% adoption_contact.errors.full_messages.each do |msg| %>
				        <li><%= msg %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>

				  	<div class="form-group">
					    <%= f.label :first_name %>
					    <%= f.text_field :first_name, :class => "form-control" %>
					  </div>
					  <div class="form-group">
					    <%= f.label :last_name %>
					    <%= f.text_field :last_name, :class => "form-control" %>
					  </div>
					  <div class="form-group">
					    <%= f.label :address %>
					    <%= f.text_field :address, :class => "form-control" %>
					  </div>
					  <div class="form-group">
					    <%= f.label :phone %>
					    <%= f.text_field :phone, :class => "form-control" %>
					  </div>
					  <div class="form-group">
					    <%= f.label :email %>
					    <%= f.text_field :email, :class => "form-control" %>
					  </div>

						<hr />
				    <%= f.submit "Add Adoption Contact", :class => "btn btn-primary submit-button" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/admin/adoption_contacts/edit.html.erb
<h1>Editing adoption_contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @adoption_contact %> |
<%= link_to 'Back', adoption_contacts_path %>

app/views/admin/adoption_contacts/index.html.erb
<div class="row">
	<div class="col-sm-12 col-md-12 col-lg-12">
		<!-- <div class="block-flat"> -->
			<a class="btn btn-primary btn-rad btn-trans" href="/admin/adoption_contacts/new"><i class="fa fa-plus tipster" title="Add New"></i><span class="hidden-xs hidden-sm"> Add New Adoption Contact</span></a>
			&nbsp;
			<a class="btn btn-primary btn-rad btn-trans" href="/admin/adoption_contacts.csv" id="animal_sync_button"><i class="fa fa-download tipster" title="Export"></i> <span class="hidden-xs hidden-sm">Export</span></a>
			&nbsp;
			<%= link_to raw('<i class="fa fa-file tipster" title="Download Adoption Form"></i> <span class="hidden-xs hidden-sm">Download Adoption Form</span>'), current_user.organization.adoption_form.url, :class => "btn btn-primary btn-rad btn-trans" %>
			<a class="btn btn-primary btn-rad btn-trans pull-right" data-toggle="modal" href="#myModal" ><i class="fa fa-search tipster" title="Search"></i> <span class="hidden-xs hidden-sm">Advanced Search</span></a>
		<!-- </div> -->
	</div>
</div>
<div class="row">
	<div class="col-sm-12 col-md-12 col-lg-12">
		<div class="block-flat">
			<table class="no-border">
				<col><col><col><col><col><col><col><col>
				<thead class="no-border">
					<tr>
						<th><%= sort_link @presenter.search, :first_name %></th>
						<th><%= sort_link @presenter.search, :last_name %></th>
						<th class="hidden-xs hidden-sm hidden-md"><%= sort_link @presenter.search, :address %></th>
						<th class="hidden-xs hidden-sm"><%= sort_link @presenter.search, :phone %></th>
						<th class="hidden-xs"><%= sort_link @presenter.search, :email %></th>
						<th></th>
					</tr>
				</thead>
				<tbody class="no-border-x no-border-y">
					<% @presenter.adoption_contacts.each do |adoption_contact| %>
						<tr>
							<td><a href="/admin/adoption_contacts/<%= adoption_contact.id %>"><%= adoption_contact.first_name %></a></td>
							<td><%= adoption_contact.last_name %></td>
							<td class="hidden-xs hidden-sm hidden-md"><%= adoption_contact.address %></td>
							<td class="hidden-xs hidden-sm"><%= number_to_phone(adoption_contact.phone) %></td>
							<td class="hidden-xs"><%= adoption_contact.email %></td>
							<td class="actions_column">
								<div class="btn-group">
									<a class="btn tipster" href="/admin/adoption_contacts/<%= adoption_contact.id %>" title="View Contact"><i class="fa fa-eye"></i></a>
									<% if can? :destroy, adoption_contact %>
										<%= link_to raw("<i class='fa fa-remove'></i>"), admin_adoption_contact_path(adoption_contact),
										            :data => {:confirm => 'Are you sure you want to delete?'}, :method => :delete, :class => "btn tipster", :title => "Delete" %>
									<% end %>
								</div>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
				<%= will_paginate @presenter.adoption_contacts, renderer: BootstrapPagination::Rails %>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal colored-header" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
				<a class="close" data-dismiss="modal" href="#">×</a>
				<h3>Advanced Search</h3>
      </div>
      <div class="modal-body" style="overflow:hidden;">
				<%= search_form_for @presenter.search, :url => admin_adoption_contacts_path, :html => {:role => "form"} do |f| %>
					<div class="form-group">
						<%= f.label :first_name_cont %>
						<%= f.text_field :first_name_cont, :class => "form-control" %>
					</div>
					<div class="form-group">
						<%= f.label :last_name_cont %>
						<%= f.text_field :last_name_cont, :class => "form-control" %>
					</div>
					<div class="form-group">
						<%= f.label :address_cont %>
						<%= f.text_field :address_cont, :class => "form-control" %>
					</div>
					<div class="form-group">
						<%= f.label :phone_cont %>
						<%= f.text_field :phone_cont, :class => "form-control" %>
					</div>
					<div class="form-group">
						<%= f.label :email_cont %>
						<%= f.text_field :email_cont, :class => "form-control" %>
					</div>

					<div class="form-group">
						<%= f.label :animals_id_eq, "Animal" %>
						<%= f.collection_select :animals_id_eq, @presenter.animal, :id, :name, :include_blank => true, :class => "form-control modal-select" %>
					</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Submit", :class => "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/adoption_contacts/new.html.erb
<div class="row">
	<div class="col-sm-12 col-md-12 col-lg-12 main-app-row">
		<div class="block-flat">
			<h1>New adoption contact</h1>
		</div>

		<%= render 'form', :adoption_contact => @adoption_contact  %>


	</div>
</div>

app/views/admin/adoption_contacts/show.html.erb
<div class="row">
	<div class="col-sm-12 col-md-12 col-lg-12 main-app-row">
		<div class="block-flat profile-info">
      <div class="row">
        <div class="col-sm-11 col-md-11 col-lg-11">
          <div class="col-sm-2 col-md-2 col-lg-1">
            <div class="avatar">
              <%= gravatar_image_tag(@adoption_contact.email, alt: @adoption_contact.email, gravatar: { size: 260 }, class: 'profile-avatar') %>
            </div>
          </div>
          <div class="col-sm-10 col-md-10 col-lg-10">
            <div class="personal">
              <h1><%= best_in_place @adoption_contact, :first_name, :type => :input, :nil => "Click me to add content!", :path => admin_adoption_contact_path %>
              <%= best_in_place @adoption_contact, :last_name, :type => :input, :nil => "", :path => admin_adoption_contact_path %></h1>
            </div>
          </div>
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1 pull-right share-animal-buttons">
          <%= link_to raw('<i class="fa fa-download"></i> Download Contact'), admin_adoption_contact_path(@adoption_contact, format: :vcf), class: 'btn btn-primary btn-rad btn-trans pull-right' %>
        </div>
      </div>
		</div>
		<div class="row">
			<div class="tabbable col-sm-12 col-md-12 col-lg-6 ">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#1" data-toggle="tab">Overview</a></li>
					<li><a href="#2" data-toggle="tab">Animals</a></li>
					<li><a href="#5" data-toggle="tab">Notes</a></li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active" id="1">
						<div class="">
							<p><strong>Phone #:</strong> <%= best_in_place @adoption_contact, :phone, :nil => "Click me to add content!", :display_as => :formatted_phone, :path => admin_adoption_contact_path %></p>
							<p><strong>Email:</strong> <%= best_in_place @adoption_contact, :email, :nil => "Click me to add content!", :path => admin_adoption_contact_path %></p>
							<p><strong>Address:</strong> <%= best_in_place @adoption_contact, :address, :nil => "Click me to add content!", :path => admin_adoption_contact_path %></p>
						</div>
					</div>
					<div class="tab-pane" id="2">
						<% @animals.each do |animal| %>
							<p>
								<%= link_to raw("<i class='fa fa-remove'></i>"), "/admin/adopt_animals/#{animal.id}?adopt=#{@adoption_contact.id}", :method => :delete, :class => "pull-right tooltip-class", :rel => "tooltip", :title => "Remove Animal"  %> <a href="/admin/animals/<%= animal.id %>"><%= animal.name %></a>
								<% if animal.adopted_date.present? %>
									<span style='font-size:12px;'> Adopted on: <%= animal.adopted_date.strftime("%m/%d/%Y") %></span>
								<% end %>
							</p>
						<%end%>
						<hr />
						<a class="btn btn-primary btn-rad btn-trans" data-toggle="modal" href="#newAnimal" ><i class="fa fa-plus"></i> Add Animal</a>
					</div>
					<div class="tab-pane" id="4">
						<div class="">
							<div id="weight_graph_holder"><canvas id="canvasWeight" height="300" width="250"></canvas></div>
							<hr />
							<a class="btn" data-toggle="modal" href="#newWeight" ><i class="fa fa-plus"></i> Add New Weight</a>
						</div>
					</div>
					<div class="tab-pane" id="5">
						<ul class="unstyled" id="animal_notes_list">
							<%unless @contact_notes.blank?%>
									<%@contact_notes.each do |note| %>
										<li><%= link_to raw("<i class='fa fa-remove'></i>"), admin_contact_note_path(note), :method => :delete, :class => "pull-right tipster", :rel => "tooltip", :title => "Delete Note"  %><strong><%= note.username %></strong> <%= note.created_at.strftime("%a, %b %e %Y at %I:%m%p") %> <br /><%= raw(sanitize(note.note)) %></li>
									<%end%>
							<%end%>
						</ul>
						<hr />
						<h2>Say something!</h2>
						<%= form_for ContactNote.new, :url => admin_contact_notes_path, :remote => true, :html => {:id => "new_note_#{current_user.id}"} do |f| %>
							<%= f.text_area :note, :rows => 5, :style => "width:95%;" %>
							<%= f.hidden_field :noteable_id, :value => @adoption_contact.id %>
							<%= f.hidden_field :noteable_type, :value => 'AdoptionContact' %><br />
							<%= f.submit "Add Note", :class => "btn btn-primary submit-button" %>
						<% end %>
					</div>
				</div>
			</div>

			<div class="col-sm-12 col-md-12 col-lg-6 map-block">
				<div id="map_canvas" style="height:409px;width:100%;"></div>
			</div>
		</div>
	</div>
</div>

<div class="modal colored-header" id="newAnimal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
				<a class="close" data-dismiss="modal" href="#">×</a>
				<h3>Add Animal</h3>
      </div>
      <div class="modal-body" style="overflow:hidden;">
				<%= form_for @adoption_contact.adopt_animals.build(:adoption_contact_id => @adoption_contact.id), :url => admin_adopt_animals_path do |f| %>

					<div class="form-group">
						<%= f.hidden_field :adoption_contact_id %>
						<%= collection_select(:adopt_animal, :animal_id, @adoptable_animals, :id, :name) %>
						<%= f.label :adopted_date %>
						<%= f.text_field :adopted_date, :class => "form-control" %>
					</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Submit", :class => "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>





<% content_for :javascript_footer do %>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" nonce=<%= content_security_policy_nonce(:script) %>>
		// Trigger the google map
		google_map('<%= @adoption_contact.address %>', '<%= @adoption_contact.first_name %>');
		// Trigger juggernaut
		// juggernaut_listen('<%= @adoption_contact.id %>', 'adoption_contact', 'adopt_contact');
		hos_cable_listen('<%= @adoption_contact.id %>', 'adoption_contact', 'adopt_contact');
		contact_note_cable_listen('<%= @adoption_contact.id %>', 'adoption_contact', 'adopt_contact');
		$( "#adopt_animal_adopted_date" ).datepicker();
    // $( "#shot_expires" ).datepicker({yearRange: "-50:+50"});
    $.datepicker.setDefaults({
      dateFormat: 'D, dd M yy'
    });
	</script>
<% end %>

app/views/admin/adoption_contacts/show.vcf.erb
<%= generate_vcard(@adoption_contact) %>