config/routes.rb
AnimalTracker::Application.routes.draw do
  mount ActionCable.server => '/cable'
  resource :facebook_accounts, only: [:new, :destroy]
  get 'callback/facebook/:id', to: 'facebook_accounts#callback', as: :facebook_callback
  post 'facebook_accounts/send_wall_post', to: 'facebook_accounts#send_wall_post'
  delete 'facebook_accounts/:id', to: 'facebook_accounts#destroy'

  resource :twitter_accounts, only: [:new, :destroy]
  get 'callback/twitter', to: 'twitter_accounts#callback', as: :twitter_callback
  post 'twitter_accounts/send_tweet', to: 'twitter_accounts#send_tweet'
  delete 'twitter_accounts/:id', to: 'twitter_accounts#destroy'

  get '/animals/not_available', to: 'animals#not_available'
  resources :animals, only: [:show, :index]

  resources :organizations, only: [:show]

  resources :posts, only: [:show, :index]

  post 'wordpress_accounts/send_blog_post', to: 'admin/wordpress_accounts#send_blog_post'
  get 'send-to-adopt-a-pet', to: 'admin/adopt_a_pet_accounts#send_animal'

  devise_for :users
  get 'home/index'
  root to: 'home#index'
  get 'about', to: 'home#about'
  get 'features', to: 'home#features'
  get 'privacy-and-terms-of-service', to: 'home#privacy'
  get 'why-hospitium', to: 'home#why'
  get 'recent-changes', to: 'home#changes'
  get 'posts/feed/rss', to: 'posts#feed'

  devise_scope :user do
    put 'users/:id', to: 'users#update'
    delete 'users/sign_out', to: 'devise/session#destroy'
  end

  # Prefix route urls with "admin"
  namespace :admin do
    root to: 'home#index'

    resources :species,
              :statuses,
              :animal_colors,
              :shelters,
              :animal_weights,
              :adoption_contacts,
              :organizations,
              :relinquishment_contacts,
              :vet_contacts,
              :volunteer_contacts,
              :notifications,
              :posts,
              :notes,
              :documents,
              :shots,
              :adopt_a_pet_accounts,
              :wordpress_accounts,
              :adopt_animals,
              :relinquish_animals,
              :foster_contacts,
              :foster_animals,
              :contact_notes

    resources :animals do
      resources :animal_weights, :documents, :shots, :notes, :adoption_contacts, :relinquishment_contacts
      member do
        get 'cage_card'
        get 'duplicate'
        get 'qr_code'
        patch 'add_image'
      end
    end

    resources :users do
      member do
        get 'reset_token', to: 'users#reset_token'
        put 'set_role', to: 'users#set_role', as: 'user_role'
        delete 'cancel', to: 'users#cancel', as: 'cancel_user'
      end
    end
  end

  # post SecureHeaders::ContentSecurityPolicy::FF_CSP_ENDPOINT => 'content_security_policy#scribe'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  # include PublicActivity::Model
  # tracked owner: -> controller, model { controller.current_user },
  #         recipient: -> controller, model { controller.current_user.organization },
  #         params: {
  #           author_name: -> controller, model { controller.current_user.username },
  #           author_email: -> controller, model { controller.current_user.email },
  #           object_name: -> controller, model { model.name },
  #           summary: -> controller, model { model.changes }
  #         }

  ORGANIZATION_FORM_OPTIONS = {
    storage: :s3,
    s3_protocol: 'https',
    s3_credentials: { access_key_id: ENV['S3_KEY'], secret_access_key: ENV['S3_SECRET'] },
    bucket: 'hospitium-static-v2',
    url: '/system/:attachment/:hash/:filename',
    hash_secret: ENV['SALTY']
  }.freeze

  has_attached_file :adoption_form,
                    ORGANIZATION_FORM_OPTIONS.merge(default_url: 'https://d4uktpxr9m70.cloudfront.net/pdfs/Adoption-Form.pdf')
  has_attached_file :volunteer_form,
                    ORGANIZATION_FORM_OPTIONS.merge(default_url: 'https://d4uktpxr9m70.cloudfront.net/pdfs/Volunteer-Application.pdf')
  has_attached_file :relinquishment_form,
                    ORGANIZATION_FORM_OPTIONS
  has_attached_file :foster_form,
                    ORGANIZATION_FORM_OPTIONS
  validates_attachment_content_type :adoption_form, content_type: ['application/pdf',
                                                                   'application/msword',
                                                                   'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                                                                   'application/vnd.openxmlformats-officedocument.wordprocessingml.template']

  has_many :adoption_contacts, dependent: :destroy
  has_many :animals, dependent: :destroy
  has_many :animal_colors, dependent: :destroy
  has_many :animal_weights, dependent: :destroy
  has_many :documents
  has_many :facebook_accounts, dependent: :destroy
  has_many :relinquishment_contacts, dependent: :destroy
  has_many :shelters, dependent: :destroy
  has_many :shots, dependent: :destroy
  has_many :species, dependent: :destroy
  has_many :statuses, dependent: :destroy
  has_many :twitter_accounts, dependent: :destroy
  has_many :vet_contacts, dependent: :destroy
  has_many :volunteer_contacts, dependent: :destroy
  has_many :wordpress_accounts, dependent: :destroy
  has_many :foster_contacts, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :contact_notes, dependent: :destroy

  before_update :modify_phone_number
  after_create :add_default_status, :add_default_animal_colors, :add_default_species

  attr_accessible :name, :phone_number, :address, :city, :state, :zip_code, :email, :website, :adoption_form, :volunteer_form, :relinquishment_form, :foster_form

  validates :name, uniqueness: true

  # create the default statuses and assign them to the new organization
  def add_default_status
    ['Adoptable', 'New Intake', 'Sanctuary', 'Sick', 'Deceased', 'Adopted', 'Foster Care'].each do |status_name|
      status = Status.new(status: status_name)
      status.organization_id = id
      status.save
    end
  end

  # create the default animal colors and assign them to the new organization
  def add_default_animal_colors
    %w(Black White Gray Brown).each do |color_name|
      animal_color = AnimalColor.new(color: color_name)
      animal_color.organization_id = id
      animal_color.save
    end
  end

  # create the default species and assign them to the new organization
  def add_default_species
    %w(Cat Dog Hamster Gerbil Chinchilla Bird Rat Mouse).each do |species_name|
      species = Species.new(name: species_name)
      species.organization_id = id
      species.save
    end
  end

  def modify_phone_number
    # unless self.phone_number.blank?
    self.phone_number = phone_number.delete('^0-9') unless phone_number.blank?
    # end
  end

  def formatted_phone
    phone_number.blank? ? '' : number_to_phone(phone_number)
  end

  def has_info?
    return false if phone_number.blank? && email.blank? && website.blank?
    true
  end

  def full_address
    "#{address} #{city} #{state} #{zip_code}"
  end

  def owner
    User.where(organization_id: id, owner: 1).first
  end

  def pretty_website
    if website && !url_protocol_present?
      "http://#{website}"
    else
      website
    end
  end

  private

  def url_protocol_present?
    website[/\Ahttp:\/\//] || website[/\Ahttps:\/\//]
  end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < Admin::ApplicationController
  load_and_authorize_resource
  skip_before_action :authenticate_user_from_token!, except: [:index, :show]
  # include PublicActivity::StoreController

  respond_to :html, :json

  def index
    @organizations = Organization.where(id: current_user.organization_id)

    respond_with(@organizations)
  end

  def update
    @organization = Organization.where(id: current_user.organization_id).first
    @organization.update_attributes(organization_params)

    flash[:success] = 'Update successful'
    respond_with(@organization, location: admin_organizations_path)
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :phone_number, :address, :city, :state, :zip_code, :email, :website, :adoption_form, :volunteer_form, :relinquishment_form, :foster_form)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  respond_to :html, :json

  def show
    canonical_url("/organizations/#{params[:id]}")
    @organization = Rails.cache.fetch("public_org_#{params[:id]}", expires_in: 15.minutes) do
      Organization.find(params[:id])
    end
    @animals = Rails.cache.fetch("public_org_animals_#{params[:id]}", expires_in: 15.minutes) do
      Animal.where(public: 1, organization_id: @organization.id)
    end

    respond_with(@organization)
  end
end

app/views/admin/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :uuid %><br />
    <%= f.text_field :uuid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/admin/organizations/index.html.erb
<% @organizations.each do |organization| %>
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12 main-app-row">
				<div class="block-flat profile-info">
					<div class="row">
            <div class="col-sm-2 col-md-2 col-lg-1">
              <div class="avatar">
                <%= gravatar_image_tag("#{organization.email}", :alt => "#{organization.email}", :gravatar => { :size => 260 }, :class => "profile-avatar") %>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="personal">
						    <h1><%= best_in_place organization, :name, :type => :input, :nil => "Click me to add content!", :path => admin_organization_path(organization) %></h1>
              </div>
            </div>
            <div class="col-sm-3 hidden-xs hidden-sm">
  						<% if can? :cancel, current_user %>
  							<%= link_to raw("<i class='fa fa-remove'></i> Cancel Account"), cancel_user_admin_user_path(current_user),
  		                            :data => {:confirm => 'Are you sure you want to delete? This will remove all animals, users, and other data associated with your Organization. This action can not be undone.'}, :method => :delete, :class => "btn btn-primary btn-rad btn-trans pull-right tipster", :title => "Delete" %>
  						<% end %>
            </div>
					</div>
				</div>
				<div class="row">
					<div class="tabbable col-sm-6 col-md-6 col-lg-6">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#1" data-toggle="tab">Details</a></li>
						</ul>
						<div class="tab-content">
							<div class="tab-pane active" id="1">
								<div class="">
									<p><strong>Website:</strong> <%= best_in_place organization, :website, :type => :input, :nil => "Click me to add content!", :path => admin_organization_path(organization) %></p>
									<p><strong>Email:</strong> <%= best_in_place organization, :email, :type => :input, :nil => "Click me to add content!", :path => admin_organization_path(organization) %></p>
									<p><strong>Phone #:</strong> <%= best_in_place organization, :phone_number, :type => :input, :nil => "Click me to add content!", :display_as => :formatted_phone, :path => admin_organization_path(organization) %></p>
									<p><strong>Street:</strong> <%= best_in_place organization, :address, :type => :input, :nil => "Click me to add content!", :path => admin_organization_path(organization) %></p>
									<p><strong>City:</strong> <%= best_in_place organization, :city, :type => :input, :nil => "Click me to add content!", :path => admin_organization_path(organization) %></p>
									<p><strong>State:</strong> <%= best_in_place organization, :state, :type => :input, :nil => "Click me to add content!", :path => admin_organization_path(organization) %></p>
									<p><strong>Zip:</strong> <%= best_in_place organization, :zip_code, :type => :input, :nil => "Click me to add content!", :path => admin_organization_path(organization) %></p>
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-6 col-md-6 col-lg-6 map-block">
						<div id="map_canvas" style="height:409px;width:100%;"></div>
					</div>
				</div>
		</div>
	</div>

<a class="btn" data-toggle="modal" href="#adoption_form" ><i class="fa fa-plus"></i> Add Adoption Form</a>
<a class="btn" data-toggle="modal" href="#volunteer_form" ><i class="fa fa-plus"></i> Add Volunteer Form</a>
<a class="btn" data-toggle="modal" href="#relinquishment_form" ><i class="fa fa-plus"></i> Add Relinquishment Form</a>
<a class="btn" data-toggle="modal" href="#foster_form" ><i class="fa fa-plus"></i> Add Foster Form</a>

<div class="modal colored-header" id="adoption_form" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
				<a class="close" data-dismiss="modal" href="#">×</a>
				<h3>Add New Adoption Form</h3>
      </div>
      <div class="modal-body" style="overflow:hidden;">
				<div class="progress progress-striped active adoption_form_upload_bar" style="display:none;">
					<div class="progress-bar progress-bar-danger" style="width: 100%;"></div>
				</div>
				<p class="adoption_form_upload_bar" style="display:none;">Loading...</p>
				<%= form_for organization, :url => admin_organization_path(organization.id), :html => { :id => "adoption_form_upload" }, :validate => true do |f| %>
					<%= f.file_field :adoption_form, :accept => "application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.wordprocessingml.template" %>
				<%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a href="#" class="btn btn-primary submit-button" data-form-id="adoption_form_upload">Save changes</a>
      </div>
    </div>
  </div>
</div>

<div class="modal colored-header" id="volunteer_form" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
				<a class="close" data-dismiss="modal" href="#">×</a>
				<h3>Add New Volunteer Form</h3>
      </div>
      <div class="modal-body" style="overflow:hidden;">
				<div class="progress progress-striped active volunteer_form_upload_bar" style="display:none;">
					<div class="progress-bar progress-bar-danger" style="width: 100%;"></div>
				</div>
				<p class="volunteer_form_upload_bar" style="display:none;">Loading...</p>
				<%= form_for organization, :url => admin_organization_path(organization.id), :html => { :id => "volunteer_form_upload" }, :validate => true do |f| %>
					<%= f.file_field :volunteer_form, :accept => "application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.wordprocessingml.template" %>
				<%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a href="#" class="btn btn-primary submit-button" data-form-id="volunteer_form_upload">Save changes</a>
      </div>
    </div>
  </div>
</div>

<div class="modal colored-header" id="relinquishment_form" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
				<a class="close" data-dismiss="modal" href="#">×</a>
				<h3>Add New Relinquishment Form</h3>
      </div>
      <div class="modal-body" style="overflow:hidden;">
				<div class="progress progress-striped active relinquishment_form_upload_bar" style="display:none;">
					<div class="progress-bar progress-bar-danger" style="width: 100%;"></div>
				</div>
				<p class="relinquishment_form_upload_bar" style="display:none;">Loading...</p>
				<%= form_for organization, :url => admin_organization_path(organization.id), :html => { :id => "relinquishment_form_upload" }, :validate => true do |f| %>
					<%= f.file_field :relinquishment_form, :accept => "application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.wordprocessingml.template" %>
				<%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a href="#" class="btn btn-primary submit-button" data-form-id="relinquishment_form_upload">Save changes</a>
      </div>
    </div>
  </div>
</div>

<div class="modal colored-header" id="foster_form" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
				<a class="close" data-dismiss="modal" href="#">×</a>
				<h3>Add New Foster Form</h3>
      </div>
      <div class="modal-body" style="overflow:hidden;">
				<div class="progress progress-striped active foster_form_upload_bar" style="display:none;">
					<div class="progress-bar progress-bar-danger" style="width: 100%;"></div>
				</div>
				<p class="foster_form_upload_bar" style="display:none;">Loading...</p>
				<%= form_for organization, :url => admin_organization_path(organization.id), :html => { :id => "foster_form_upload" }, :validate => true do |f| %>
					<%= f.file_field :foster_form, :accept => "application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.wordprocessingml.template" %>
				<%end%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a href="#" class="btn btn-primary submit-button" data-form-id="foster_form_upload">Save changes</a>
      </div>
    </div>
  </div>
</div>

	<% content_for :javascript_footer do %>
		<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
		<script type="text/javascript" nonce=<%= content_security_policy_nonce(:script) %>>
			// Trigger google maps
			google_map('<%= organization.full_address %>', '<%= organization.name %>');
			// Trigger juggernaut
			// juggernaut_listen('<%= organization.id  %>', 'organization');
			hos_cable_listen('<%= organization.id  %>', 'organization');
		</script>
	<%end%>

<%end%>

app/views/admin/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/admin/organizations/show.html.erb
	<div class="hero-unit clearfix">
		<div class="page-header">
			<%= gravatar_image_tag("#{@organization.email}", :alt => "#{@organization.email}", :gravatar => { :size => 100 }, :style => "vertical-align:bottom;padding:5px 5px 7px 0px") %>
			<h1 style="display:inline;"><%= @organization.name %></h1>
		</div>
		<div class="otherAnimalInfo" style="width:400px;float:left">
			<h2>Contact Info</h2>
			<p>Website: <a href="<%= @organization.website %>" rel="nofollow"><%= @organization.website %></a></p>
			<p>Email: <a href="mailto:<%= @organization.email %>"><%= @organization.email %></a></p>
			<p>Phone Number: <%= number_to_phone(@organization.phone_number, :area_code => true) %></p>
			<p>Address: <%= @organization.address %></p>
			<p><%= @organization.city %> <%= @organization.state %> <%= @organization.zip_code %></p>
			<h2>Animals For Adoption</h2>
			<ul>
				<% @animals.each do |animal| %>
					<li><a class='js-pjax' href="/animals/<%= animal.id %>"><%= animal.name %></a></li>
				<% end %>
			</ul>
		</div>
		<div id="map_canvas" style="height:400px;width:400px;float:right;"></div>
	</div>
	<p id="notice"><%= notice %></p>

<br /><br />
<p style="font-size:13px;">
All information listed here is contributed by our members. Hospitium is not responsible for its contents. We assume in good faith that all Organizations are in good legal standing to adopt animals.
</p>
<% set_meta_description("#{@organization.name}: #{@organization.website}, #{@organization.phone_number}") %>
<% set_meta_keywords("adopt,animal,pets") %>
<% set_head_title("#{@organization.name}") %>
<% content_for :title, "#{@organization.name} - Hospitium" %>
<title><%= yield (:title) %></title>

<% content_for :javascript_footer do %>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" nonce=<%= content_security_policy_nonce(:script) %>>
		google_map('<%= @organization.address %> <%= @organization.city %> <%= @organization.state %> <%= @organization.zip_code %>', '<%= @organization.name %>');
	</script>
<% end %>